services:
  bot:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - tamyar
    depends_on:
      - tor

  tor:
    container_name: "tor"
    stdin_open: true
    tty: true
    ports:
        - 8118:8118
        - 9050:9050
    image: dperson/torproxy
    networks:
      - tamyar
networks:
  tamyar:
    driver: bridge